up-build-services:
	open -a Terminal . && osascript -e 'tell application "Terminal" to do script "cd ./services1 && npm install && npm run start" in window 1'
	open -a Terminal . && osascript -e 'tell application "Terminal" to do script "cd ./services2 && npm install && npm run start" in window 1'
